### ISSUE TITLE
Support to pass additional build contexts for the docker image

### ISSUE THREAD

**Issue by krassowski** [drifting-in-space/jamsocket-cli#132]
Similar to https://github.com/jamsocket/jamsocket-deploy-action/issues/3, it would be lovely if `jamsocket push` supported named contexts for building Docker.

**Comment by rolyatmax** [comment]
Sorry for the delay in getting to this, but I've just added support for additional named build contexts to the `jamsocket push` command in #144. It should work like this:

```
npx jamsocket push my-service \
   -f ./Dockerfile \
   --build-context my-named-context=/path/to/context \
   --build-context another-context=/path/to/another/context
```

@krassowski Let me know if that works for you!
