### ISSUE TITLE
Standalone proxies

### ISSUE THREAD

**Issue by paulgb** [drifting-in-space/jamsocket-cli#74]
Currently, the proxy runs inside the drone. This will move the proxy into a separate process, which can be run on a separate machine. This allows more flexibility in how we route traffic and configure clusters, and should simplify DNS quite a bit.

**Comment by rolyatmax** [comment]
From internal conversations, it seems we're leaning more towards keeping the subdomain-based routing, but possibly switch to using a proxy-per-cluster that would allow drones to run without a public IP and would also remove the need to run our own nameserver.

@paulgb, did I miss anything there?

**Comment by paulgb** [comment]
Yes, that's accurate. I've updated the issue.
